openapi: 3.0.3
info:
  title: Trading Algorithms
  description:
  version: 1.0.11

tags:
- name: Auth
  description: Authentication
- name: Configuration
  description: Get possible configurations
- name: Trading Algorithms
  description: Run simulations and benchmarks
paths:
  /:
    get:
      summary: Test
      description: Test
      operationId: test
      requestBody:
      responses:
        "200":
          description: Successful operation
        "401":
          description: Invalid username or password
  /auth:
    post:
      tags:
      - Auth
      summary: Get bearer token
      description: Get bearer token
      operationId: auth
      requestBody:
        description: Add the username and password
        content:
          application/json:
            schema:
              required:
              - username
              - password
              type: object
              properties:
                username:
                  type: string
                  example: test
                password:
                  type: string
                  example: test
              example:
                username: test
                password: test
        required: true
      responses:
        "200":
          description: Successful operation
        "401":
          description: Invalid username or password
      security:
      - bearerAuth: []
  /configuration:
    get:
      tags:
        - Configuration
      summary: Get possible configurations
      description: Get possible configurations
      operationId: configuration
      responses:
        "200":
          description: Successful operation
      security:
        - bearerAuth: []
  /simulate:
    post:
      tags:
        - Trading Algorithms
      summary: Run a simulation with the desired configuration
      description: Run a simulation with the desired configuration
      operationId: simulate
      requestBody:
        description: Add the simulation settings
        content:
          application/json:
            schema:
              required:
                - algorithm
              optional:
                - ticker
                - period
                - interval
              type: object
              properties:
                algorithm:
                  type: string
                  example: mean_reversion
                ticker:
                  type: string
                  example: AAPL
                period:
                  type: string
                  example: 12mo
                interval:
                  type: string
                  example: 1d
              example:
                algorithm: mean_reversion
                ticker: AAPL
                period: 12mo
                interval: 1d
        required: true
      responses:
        "200":
          description: Successful operation
        "401":
          description: Invalid username or password
      security:
        - bearerAuth: [ ]
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

